name: Build
on:
  push:

permissions:
  id-token: write  # Required for OIDC
  contents: read
  packages: write
  attestations: write

jobs:
  check_eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: |
        sudo npm install -g eslint@8
    - run: eslint index.js --ext .js,.jsx,.ts,.tsx
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@master
    - name: Set up Node.js
      uses: actions/setup-node@master
      with:
        node-version: 24
    - run: |
        npm install
    - run: |
        npm run-script test
  npm:
    name: npm-publish
    if: "github.event_name == 'push' "
    runs-on: ubuntu-latest
    needs: [check_eslint,test]
    steps:
    - name: Checkout repository
      uses: actions/checkout@master
    - name: Set up Node.js
      uses: actions/setup-node@master
      with:
        node-version: 24
        registry-url: 'https://registry.npmjs.org'
    - name: Install modules
      run: |
        npm install
    - name: Test (Development)
      run: npm test
    - name: Build
      run: npm run build
    - name: Test (Production)
      run: npm test
    - run: |
        ls -las src
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,' | sed -e 's/^v//')
        jq '.version="'"$VERSION"'" | .main="src/RuleParser.production.js"' package.json > /tmp/a

        mv /tmp/a package.json
    - run: |
        npm publish
      if: "startsWith(github.ref, 'refs/tags/v')"
    - uses: actions/setup-node@v2
      with:
          node-version: 24
          registry-url: https://npm.pkg.github.com/
      if: "startsWith(github.ref, 'refs/tags/v')"
    - run: |
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      if: "startsWith(github.ref, 'refs/tags/v')"